<div style="
    background: linear-gradient(135deg, #0F172A 0%, #111827 100%);
    padding: 35px;
    border-radius: 22px;
    border-bottom: 8px solid #06B6D4;
    box-shadow: 0 10px 30px rgba(15,23,42,0.35);
    font-family: Segoe UI, Arial, sans-serif;
">

<h1 style="
    color: white;
    margin: 0;
    font-size: 42px;
    font-weight: 800;
    letter-spacing: 1px;
">
NEXORA ANALYTICS
</h1>

<p style="
    color: #CBD5E1;
    font-size: 20px;
    margin-top: 12px;
    margin-bottom: 0;
">
Projet Global — Data Science, Détection de Fraude,
Segmentation Client et MLOps
</p>

</div>

<div style="
    background:#F8FAFC;
    padding:28px;
    border-radius:18px;
    border-left:10px solid #06B6D4;
    box-shadow:0 6px 18px rgba(15,23,42,0.10);
    font-family:Segoe UI, Arial, sans-serif;
    margin-top:20px;
">

<h1 style="
    color:#0F172A;
    margin:0;
    font-size:32px;
    font-weight:800;
">
Exercice 1 — Détection de fraude bancaire avec Machine Learning
</h1>

<p style="
    color:#475569;
    font-size:17px;
    margin-top:12px;
">
Développement d’un système intelligent capable de détecter automatiquement les transactions frauduleuses à partir de données financières.
</p>

</div>

<div style="
    border-left:6px solid #06B6D4;
    background:#ECFEFF;
    padding:14px 18px;
    border-radius:12px;
    font-family:Segoe UI;
    margin-top:20px;
">

<h3 style="
    margin:0;
    color:#0F172A;
">
2. Prétraitement
</h3>

</div>

In [1]:
# ============================================
# IMPORTATION DES LIBRAIRIES
# ============================================

import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from imblearn.over_sampling import SMOTE

import plotly.express as px

print("Librairies importées avec succès")

Librairies importées avec succès

In [2]:
# ============================================
# CHARGEMENT DES DONNÉES
# ============================================

DATA_PATH = "../data/raw/detection_fraude.csv"

df = pd.read_csv(DATA_PATH, sep=";")

print("Dataset chargé")

print(df.shape)

df.head()

Dataset chargé
(1048575, 11)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

<div style="
    display:inline-block;
    border-left:5px solid #06B6D4;
    background:#ECFEFF;
    padding:10px 14px;
    border-radius:10px;
    font-family:Segoe UI;
    margin-top:15px;
    margin-bottom:10px;
    box-shadow:0 2px 8px rgba(15,23,42,0.06);
">

<h3 style="
    margin:0;
    color:#0F172A;
    font-size:18px;
    font-weight:600;
">
 •	Gestion des valeurs manquantes
</h3>

</div>

In [3]:
# ============================================
# ANALYSE DES VALEURS MANQUANTES
# ============================================

missing_values = (
    df.isnull()
      .sum()
      .reset_index()
)

missing_values.columns = [
    "Variable",
    "Valeurs_manquantes"
]

missing_values["Pourcentage"] = (
    missing_values["Valeurs_manquantes"] / len(df)
) * 100

missing_values

          Variable  Valeurs_manquantes  Pourcentage
0             step                   0          0.0
1             type                   0          0.0
2           amount                   0          0.0
3         nameOrig                   0          0.0
4    oldbalanceOrg                   0          0.0
5   newbalanceOrig                   0          0.0
6         nameDest                   0          0.0
7   oldbalanceDest                   0          0.0
8   newbalanceDest                   0          0.0
9          isFraud                   0          0.0
10  isFlaggedFraud                   0          0.0

In [4]:
# ============================================
# VISUALISATION DES VALEURS MANQUANTES
# ============================================

fig = px.bar(
    missing_values,
    x="Variable",
    y="Pourcentage",
    color="Pourcentage",
    text="Pourcentage",

    color_continuous_scale=[
        "#06B6D4",
        "#7C3AED",
        "#0F172A"
    ],

    title="Analyse des valeurs manquantes"
)

fig.update_traces(
    texttemplate='%{text:.2f}%',
    textposition='outside'
)

fig.update_layout(
    template="plotly_white",
    height=550,
    title_x=0.5,
    coloraxis_showscale=False
)

fig.show()

<div style="
    background:#F8FAFC;
    border-left:6px solid #7C3AED;
    padding:18px 20px;
    border-radius:12px;
    margin-top:15px;
    font-family:Segoe UI;
">

<h3 style="
    margin-top:0;
    color:#0F172A;
">
Interprétation métier
</h3>

<p style="color:#334155; line-height:1.7;">

L’analyse des valeurs manquantes permet d’évaluer la qualité globale des données utilisées dans le système de détection de fraude.

Un dataset contenant peu ou pas de valeurs manquantes améliore :
</p>

<ul style="color:#334155; line-height:1.7;">
<li>la stabilité des modèles ;</li>
<li>la qualité des prédictions ;</li>
<li>la fiabilité des analyses financières.</li>
Ici nous n'avons pas de valeurs manquantes.
</ul>

</div>

<div style="
    display:inline-block;
    border-left:5px solid #06B6D4;
    background:#ECFEFF;
    padding:10px 14px;
    border-radius:10px;
    font-family:Segoe UI;
    margin-top:15px;
    margin-bottom:10px;
    box-shadow:0 2px 8px rgba(15,23,42,0.06);
">

<h3 style="
    margin:0;
    color:#0F172A;
    font-size:18px;
    font-weight:600;
">
 •	Encodage
</h3>

</div>

In [5]:
# ============================================
# ENCODAGE DES VARIABLES CATÉGORIELLES
# ============================================

categorical_columns = [
    "type",
    "nameOrig",
    "nameDest"
]

encoder = LabelEncoder()

for col in categorical_columns:
    df[col] = encoder.fit_transform(df[col])

print("Encodage terminé")

df.head()

Encodage terminé

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,3,9839.64,125164,170136.0,160296.36,274917,0.0,0.0,0,0
1,1,3,1864.28,361319,21249.0,19384.72,286716,0.0,0.0,0,0
2,1,4,181.00,165236,181.0,0.00,73550,0.0,0.0,1,0
3,1,1,181.00,961662,181.0,0.00,65464,21182.0,0.0,1,0
4,1,3,11668.14,567915,41554.0,29885.86,138001,0.0,0.0,0,0

<div style="
    background:#F8FAFC;
    border-left:6px solid #7C3AED;
    padding:18px 20px;
    border-radius:12px;
    margin-top:15px;
    font-family:Segoe UI;
">

<h3 style="
    margin-top:0;
    color:#0F172A;
">
Interprétation métier
</h3>

<p style="color:#334155; line-height:1.7;">

Les modèles de Machine Learning ne peuvent pas traiter directement les données textuelles.

L’encodage transforme les variables catégorielles en valeurs numériques exploitables par les algorithmes d’apprentissage automatique.
</p>

</div>

<div style="
    display:inline-block;
    border-left:5px solid #06B6D4;
    background:#ECFEFF;
    padding:10px 14px;
    border-radius:10px;
    font-family:Segoe UI;
    margin-top:15px;
    margin-bottom:10px;
    box-shadow:0 2px 8px rgba(15,23,42,0.06);
">

<h3 style="
    margin:0;
    color:#0F172A;
    font-size:18px;
    font-weight:600;
">
 •	Normalisation
</h3>

</div>

In [6]:
# ============================================
# NORMALISATION DES VARIABLES NUMÉRIQUES
# ============================================

numeric_columns = df.select_dtypes(
    include=np.number
).columns.tolist()

numeric_columns.remove("isFraud")

scaler = StandardScaler()

df[numeric_columns] = scaler.fit_transform(
    df[numeric_columns]
)

print("Normalisation terminée")

df.head()

Normalisation terminée

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,-1.662022,0.956576,-0.561738,-1.318453,-0.236856,-0.243833,1.220674,-0.425883,-0.461067,0,0.0
1,-1.662022,0.956576,-0.591840,-0.538096,-0.286957,-0.290675,1.315994,-0.425883,-0.461067,0,0.0
2,-1.662022,1.700067,-0.598194,-1.186038,-0.294046,-0.297118,-0.406106,-0.425883,-0.461067,1,0.0
3,-1.662022,-0.530406,-0.598194,1.445694,-0.294046,-0.297118,-0.471430,-0.416661,-0.461067,1,0.0
4,-1.662022,0.956576,-0.554837,0.144586,-0.280124,-0.287184,0.114573,-0.425883,-0.461067,0,0.0

<div style="
    display:inline-block;
    border-left:5px solid #06B6D4;
    background:#ECFEFF;
    padding:10px 14px;
    border-radius:10px;
    font-family:Segoe UI;
    margin-top:15px;
    margin-bottom:10px;
    box-shadow:0 2px 8px rgba(15,23,42,0.06);
">

<h3 style="
    margin:0;
    color:#0F172A;
    font-size:18px;
    font-weight:600;
">
 •	Gestion du déséquilibre des classes
</h3>

</div>

In [7]:
# ============================================
# SÉPARATION FEATURES / TARGET
# ============================================

X = df.drop("isFraud", axis=1)

y = df["isFraud"]

print(X.shape)
print(y.shape)

(1048575, 10)
(1048575,)

In [8]:
# ============================================
# DISTRIBUTION DES CLASSES AVANT SMOTE
# ============================================

before_smote = (
    y.value_counts()
     .reset_index()
)

before_smote.columns = [
    "Classe",
    "Nombre"
]

before_smote["Classe"] = before_smote["Classe"].map({
    0: "Normale",
    1: "Fraude"
})

fig = px.bar(
    before_smote,
    x="Classe",
    y="Nombre",
    color="Classe",
    text="Nombre",

    color_discrete_map={
        "Normale": "#06B6D4",
        "Fraude": "#7C3AED"
    },

    title="Distribution des classes avant SMOTE"
)

fig.update_layout(
    template="plotly_white",
    height=500,
    title_x=0.5
)

fig.show()

In [9]:
# ============================================
# APPLICATION DE SMOTE
# ============================================

smote = SMOTE(random_state=42)

X_resampled, y_resampled = smote.fit_resample(X, y)

print("SMOTE appliqué avec succès")

print(X_resampled.shape)
print(y_resampled.shape)

SMOTE appliqué avec succès
(2094866, 10)
(2094866,)

In [10]:
# ============================================
# DISTRIBUTION APRÈS SMOTE
# ============================================

after_smote = (
    pd.Series(y_resampled)
      .value_counts()
      .reset_index()
)

after_smote.columns = [
    "Classe",
    "Nombre"
]

after_smote["Classe"] = after_smote["Classe"].map({
    0: "Normale",
    1: "Fraude"
})

fig = px.bar(
    after_smote,
    x="Classe",
    y="Nombre",
    color="Classe",
    text="Nombre",

    color_discrete_map={
        "Normale": "#06B6D4",
        "Fraude": "#7C3AED"
    },

    title="Distribution des classes après SMOTE"
)

fig.update_layout(
    template="plotly_white",
    height=500,
    title_x=0.5
)

fig.show()

<div style="
    background:#F8FAFC;
    border-left:6px solid #7C3AED;
    padding:18px 20px;
    border-radius:12px;
    margin-top:15px;
    font-family:Segoe UI;
">

<h3 style="
    margin-top:0;
    color:#0F172A;
">
Interprétation métier
</h3>

<p style="color:#334155; line-height:1.7;">

Les transactions frauduleuses étant très rares, les modèles risquent d’apprendre principalement les comportements normaux.

L’utilisation de SMOTE permet :
</p>

<ul style="color:#334155; line-height:1.7;">
<li>d’équilibrer les classes ;</li>
<li>d’améliorer la détection des fraudes ;</li>
<li>de réduire les biais des modèles.</li>
</ul>

</div>

In [12]:
# ============================================
# SAUVEGARDE DES DONNÉES prétraitées
# ============================================

X_resampled.to_csv(
    "../data/processed/X_resampled.csv",
    index=False
)

pd.Series(y_resampled).to_csv(
    "../data/processed/y_resampled.csv",
    index=False
)

print("Données sauvegardées avec succès")

Données sauvegardées avec succès