<div style="
    background: linear-gradient(135deg, #0F172A 0%, #111827 100%);
    padding: 35px;
    border-radius: 22px;
    border-bottom: 8px solid #06B6D4;
    box-shadow: 0 10px 30px rgba(15,23,42,0.35);
    font-family: Segoe UI, Arial, sans-serif;
">

<h1 style="
    color: white;
    margin: 0;
    font-size: 42px;
    font-weight: 800;
    letter-spacing: 1px;
">
NEXORA ANALYTICS
</h1>

<p style="
    color: #CBD5E1;
    font-size: 20px;
    margin-top: 12px;
    margin-bottom: 0;
">
Projet Global — Data Science, Détection de Fraude,
Segmentation Client et MLOps
</p>

</div>

<div style="
    background:#F8FAFC;
    padding:28px;
    border-radius:18px;
    border-left:10px solid #06B6D4;
    box-shadow:0 6px 18px rgba(15,23,42,0.10);
    font-family:Segoe UI, Arial, sans-serif;
    margin-top:20px;
">

<h1 style="
    color:#0F172A;
    margin:0;
    font-size:32px;
    font-weight:800;
">
Exercice 1 — Détection de fraude bancaire avec Machine Learning
</h1>

<p style="
    color:#475569;
    font-size:17px;
    margin-top:12px;
">
Développement d’un système intelligent capable de détecter automatiquement les transactions frauduleuses à partir de données financières.
</p>

</div>

<div style="
    border-left:6px solid #06B6D4;
    background:#ECFEFF;
    padding:14px 18px;
    border-radius:12px;
    font-family:Segoe UI;
    margin-top:20px;
">

<h3 style="
    margin:0;
    color:#0F172A;
">
4. Interprétabilité des modèles et IA explicable
</h3>

</div>

In [1]:
# ============================================
# IMPORTATION DES LIBRAIRIES
# ============================================

import pandas as pd
import numpy as np

import shap

import plotly.express as px

from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import confusion_matrix

import matplotlib.pyplot as plt

print("Librairies importées avec succès")

Librairies importées avec succès

In [2]:
# ============================================
# CHARGEMENT DES DONNÉES
# ============================================

X = pd.read_csv("../data/processed/X_resampled.csv")

y = pd.read_csv("../data/processed/y_resampled.csv")

y = y.squeeze()

print(X.shape)
print(y.shape)

(2094866, 10)
(2094866,)

In [3]:
# ============================================
# TRAIN TEST SPLIT
# ============================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [4]:
# ============================================
# ENTRAINEMENT DU MODELE RANDOM FOREST (PLUS RAPIDE, STABLE ET COMPATIBLE AVEC SHAP)
# ============================================

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

print("Modèle entraîné")

Modèle entraîné

<div style="
    display:inline-block;
    border-left:5px solid #06B6D4;
    background:#ECFEFF;
    padding:10px 14px;
    border-radius:10px;
    font-family:Segoe UI;
    margin-top:15px;
    margin-bottom:10px;
    box-shadow:0 2px 8px rgba(15,23,42,0.06);
">

<h3 style="
    margin:0;
    color:#0F172A;
    font-size:18px;
    font-weight:600;
">
 •	Importance des variables 
</h3>

</div>

In [5]:
# ============================================
# IMPORTANCE DES VARIABLES
# ============================================

feature_importance = pd.DataFrame({

    "Variable": X.columns,

    "Importance": model.feature_importances_

})

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

feature_importance.head(10)

         Variable  Importance
4   oldbalanceOrg    0.234840
0            step    0.196698
5  newbalanceOrig    0.175562
2          amount    0.101408
1            type    0.094736
6        nameDest    0.079799
8  newbalanceDest    0.053882
7  oldbalanceDest    0.047470
3        nameOrig    0.015604
9  isFlaggedFraud    0.000000

In [6]:
# ============================================
# VISUALISATION DES IMPORTANCES
# ============================================

fig = px.bar(
    feature_importance.head(10),

    x="Importance",
    y="Variable",

    orientation="h",

    color="Importance",

    text="Importance",

    color_continuous_scale=[
        "#06B6D4",
        "#7C3AED",
        "#0F172A"
    ],

    title="Top 10 des variables les plus importantes"
)

fig.update_traces(
    texttemplate='%{text:.3f}',
    textposition='outside'
)

fig.update_layout(
    template="plotly_white",

    height=650,

    title_x=0.5,

    yaxis=dict(
        categoryorder="total ascending"
    ),

    coloraxis_showscale=False
)

fig.show()

<div style="
    background:#F8FAFC;
    border-left:6px solid #7C3AED;
    padding:18px 20px;
    border-radius:12px;
    margin-top:15px;
    font-family:Segoe UI;
">

<h3 style="
    margin-top:0;
    color:#0F172A;
">
Interprétation métier
</h3>

<p style="color:#334155; line-height:1.7;">

Les variables les plus importantes influencent fortement les décisions du modèle de détection de fraude.

Ces variables permettent :
</p>

<ul style="color:#334155; line-height:1.7;">
<li>d’identifier les comportements financiers suspects ;</li>

<li>de mieux comprendre les mécanismes de fraude ;</li>

<li>d’améliorer les stratégies de surveillance bancaire.</li>
</ul>

</div>

<div style="
    display:inline-block;
    border-left:5px solid #06B6D4;
    background:#ECFEFF;
    padding:10px 14px;
    border-radius:10px;
    font-family:Segoe UI;
    margin-top:15px;
    margin-bottom:10px;
    box-shadow:0 2px 8px rgba(15,23,42,0.06);
">

<h3 style="
    margin:0;
    color:#0F172A;
    font-size:18px;
    font-weight:600;
">
 •	SHAP 
</h3>

</div>

In [7]:
# ============================================
# CREATION DUSHAP EXPLAINER
# ============================================

explainer = shap.TreeExplainer(model)

sample_data = X_test.sample(1000, random_state=42)

shap_values = explainer.shap_values(sample_data)

print("Valeurs SHAP calculées")

Valeurs SHAP calculées

In [10]:
# ============================================
# VISUALISATION INTERACTIVE SHAP — VERSION CORRIGÉE
# ============================================

# Cas 1 : SHAP retourne une liste par classe
if isinstance(shap_values, list):
    shap_array = shap_values[1]

# Cas 2 : SHAP retourne un tableau 3D : lignes x variables x classes
elif len(np.array(shap_values).shape) == 3:
    shap_array = shap_values[:, :, 1]

# Cas 3 : SHAP retourne directement un tableau 2D
else:
    shap_array = shap_values

# Moyenne absolue des valeurs SHAP par variable
shap_importance = np.abs(shap_array).mean(axis=0)

# Création du DataFrame
shap_df = pd.DataFrame({
    "Variable": sample_data.columns,
    "Importance_SHAP": shap_importance
})

# Tri décroissant
shap_df = shap_df.sort_values(
    by="Importance_SHAP",
    ascending=False
)

# Top 15 variables
top_shap = shap_df.head(15)

# Visualisation Plotly
fig = px.bar(
    top_shap,
    x="Importance_SHAP",
    y="Variable",
    orientation="h",
    color="Importance_SHAP",
    text="Importance_SHAP",
    color_continuous_scale=[
        "#06B6D4",
        "#7C3AED",
        "#0F172A"
    ],
    title="Importance des variables selon SHAP"
)

fig.update_traces(
    texttemplate='%{text:.4f}',
    textposition='outside'
)

fig.update_layout(
    template="plotly_white",
    height=700,
    title_x=0.5,
    font=dict(
        family="Segoe UI",
        size=14,
        color="#1E293B"
    ),
    yaxis=dict(
        categoryorder="total ascending"
    ),
    plot_bgcolor="#FFFFFF",
    paper_bgcolor="#FFFFFF",
    coloraxis_showscale=False
)

fig.show()

<div style="
    background:#F8FAFC;
    border-left:6px solid #7C3AED;
    padding:18px 20px;
    border-radius:12px;
    margin-top:15px;
    font-family:Segoe UI;
">

<h3 style="
    margin-top:0;
    color:#0F172A;
">
Interprétation métier
</h3>

<p style="color:#334155; line-height:1.7;">

L’analyse SHAP permet d’expliquer individuellement les décisions prises par le modèle d’intelligence artificielle.

Cette approche améliore :
</p>

<ul style="color:#334155; line-height:1.7;">
<li>la transparence des modèles ;</li>

<li>la confiance dans les prédictions ;</li>

<li>la compréhension des comportements frauduleux.</li>
</ul>

</div>

<div style="
    display:inline-block;
    border-left:5px solid #06B6D4;
    background:#ECFEFF;
    padding:10px 14px;
    border-radius:10px;
    font-family:Segoe UI;
    margin-top:15px;
    margin-bottom:10px;
    box-shadow:0 2px 8px rgba(15,23,42,0.06);
">

<h3 style="
    margin:0;
    color:#0F172A;
    font-size:18px;
    font-weight:600;
">
 •	Analyse des faux positifs/faux négatifs. 
</h3>

</div>

In [11]:
# ============================================
# MATRICE DE CONFUSION
# ============================================

y_pred = model.predict(X_test)

cm = confusion_matrix(
    y_test,
    y_pred
)

cm_df = pd.DataFrame(
    cm,

    index=[
        "Réel Normal",
        "Réel Fraude"
    ],

    columns=[
        "Prédit Normal",
        "Prédit Fraude"
    ]
)

cm_df

             Prédit Normal  Prédit Fraude
Réel Normal         209055             65
Réel Fraude              9         209845

In [12]:
# ============================================
# VISUALISATION MATRICE DE CONFUSION
# ============================================

fig = px.imshow(
    cm_df,

    text_auto=True,

    color_continuous_scale=[
        "#ECFEFF",
        "#7C3AED",
        "#0F172A"
    ],

    title="Matrice de confusion du modèle"
)

fig.update_layout(
    template="plotly_white",

    height=600,

    title_x=0.5
)

fig.show()

<div style="
    background:#F8FAFC;
    border-left:6px solid #7C3AED;
    padding:18px 20px;
    border-radius:12px;
    margin-top:15px;
    font-family:Segoe UI;
">

<h3 style="
    margin-top:0;
    color:#0F172A;
">
Interprétation métier
</h3>

<p style="color:#334155; line-height:1.7;">

Les faux positifs correspondent aux transactions normales détectées à tort comme frauduleuses.

Les faux négatifs représentent les fraudes non détectées par le système.
</p>

<p style="color:#334155; line-height:1.7;">

Dans un contexte bancaire :
</p>

<ul style="color:#334155; line-height:1.7;">
<li>trop de faux positifs peuvent gêner les clients ;</li>

<li>les faux négatifs peuvent entraîner des pertes financières importantes.</li>
</ul>

<p style="color:#334155; line-height:1.7;">

L’objectif est donc d’équilibrer précision et détection efficace des fraudes.
</p>

</div>