<div style="
    background: linear-gradient(135deg, #0F172A 0%, #111827 100%);
    padding: 35px;
    border-radius: 22px;
    border-bottom: 8px solid #06B6D4;
    box-shadow: 0 10px 30px rgba(15,23,42,0.35);
    font-family: Segoe UI, Arial, sans-serif;
">

<h1 style="
    color: white;
    margin: 0;
    font-size: 42px;
    font-weight: 800;
    letter-spacing: 1px;
">
NEXORA ANALYTICS
</h1>

<p style="
    color: #CBD5E1;
    font-size: 20px;
    margin-top: 12px;
    margin-bottom: 0;
">
Projet Global — Data Science, Détection de Fraude,
Segmentation Client et MLOps
</p>

</div>

<div style="
    background:#F8FAFC;
    padding:28px;
    border-radius:18px;
    border-left:10px solid #06B6D4;
    box-shadow:0 6px 18px rgba(15,23,42,0.10);
    font-family:Segoe UI, Arial, sans-serif;
    margin-top:20px;
">

<h1 style="
    color:#0F172A;
    margin:0;
    font-size:32px;
    font-weight:800;
">
Exercice 2 — Segmentation intelligente des clients avec Clustering
</h1>

<p style="
    color:#475569;
    font-size:17px;
    margin-top:12px;
">
Préparation des données afin d’optimiser la qualité des futurs algorithmes de clustering.
</p>

</div>

<div style="
    border-left:6px solid #06B6D4;
    background:#ECFEFF;
    padding:14px 18px;
    border-radius:12px;
    font-family:Segoe UI;
    margin-top:20px;
">

<h3 style="
    margin:0;
    color:#0F172A;
">
2. Prétraitement
</h3>

</div>

In [1]:
# ============================================
# IMPORTATION DES LIBRAIRIES
# ============================================

import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.decomposition import PCA

import plotly.express as px

print("Librairies importées avec succès")

Librairies importées avec succès

In [2]:
# ============================================
# CHARGEMENT DES DONNÉES
# ============================================

DATA_PATH = "../data/raw/data_cluster.csv"

df = pd.read_csv(DATA_PATH, sep=";")

print("Dataset chargé")

print(df.shape)

df.head()

Dataset chargé
(2240, 29)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04/09/2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08/03/2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21/08/2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10/02/2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19/01/2014,94,173,...,5,0,0,0,0,0,0,3,11,0

<div style="
    display:inline-block;
    border-left:5px solid #06B6D4;
    background:#ECFEFF;
    padding:10px 14px;
    border-radius:10px;
    font-family:Segoe UI;
    margin-top:15px;
    margin-bottom:10px;
    box-shadow:0 2px 8px rgba(15,23,42,0.06);
">

<h3 style="
    margin:0;
    color:#0F172A;
    font-size:18px;
    font-weight:600;
">
. Gestion des valeurs manquantes
</h3>

</div>

In [3]:
# ============================================
# VALEURS MANQUANTES
# ============================================

missing_values = (
    df.isnull()
      .sum()
      .reset_index()
)

missing_values.columns = [
    "Variable",
    "Valeurs_manquantes"
]

missing_values["Pourcentage"] = (
    missing_values["Valeurs_manquantes"] / len(df)
) * 100

missing_values

               Variable  Valeurs_manquantes  Pourcentage
0                    ID                   0     0.000000
1            Year_Birth                   0     0.000000
2             Education                   0     0.000000
3        Marital_Status                   0     0.000000
4                Income                  24     1.071429
5               Kidhome                   0     0.000000
6              Teenhome                   0     0.000000
7           Dt_Customer                   0     0.000000
8               Recency                   0     0.000000
9              MntWines                   0     0.000000
10            MntFruits                   0     0.000000
11      MntMeatProducts                   0     0.000000
12      MntFishProducts                   0     0.000000
13     MntSweetProducts                   0     0.000000
14         MntGoldProds                   0     0.000000
15    NumDealsPurchases                   0     0.000000
16      NumWebPurchases                   0     0.000000
17  NumCatalogPurchases                   0     0.000000
18    NumStorePurchases                   0     0.000000
19    NumWebVisitsMonth                   0     0.000000
20         AcceptedCmp3                   0     0.000000
21         AcceptedCmp4                   0     0.000000
22         AcceptedCmp5                   0     0.000000
23         AcceptedCmp1                   0     0.000000
24         AcceptedCmp2                   0     0.000000
25             Complain                   0     0.000000
26        Z_CostContact                   0     0.000000
27            Z_Revenue                   0     0.000000
28             Response                   0     0.000000

In [4]:
# ============================================
# VISUALISATION DES VALEURS MANQUANTES
# ============================================

fig = px.bar(
    missing_values,

    x="Variable",
    y="Pourcentage",

    color="Pourcentage",

    text="Pourcentage",

    color_continuous_scale=[
        "#06B6D4",
        "#7C3AED",
        "#0F172A"
    ],

    title="Analyse des valeurs manquantes"
)

fig.update_traces(
    texttemplate='%{text:.2f}%',
    textposition='outside'
)

fig.update_layout(
    template="plotly_white",

    height=550,

    title_x=0.5,

    coloraxis_showscale=False
)

fig.show()

In [5]:
# ============================================
# IMPUTATION DES VALEURS MANQUANTES
# ============================================

numeric_columns = df.select_dtypes(
    include=np.number
).columns

for col in numeric_columns:

    df[col] = df[col].fillna(
        df[col].median()
    )

print("Valeurs manquantes traitées")

Valeurs manquantes traitées

<div style="
    background:#F8FAFC;
    border-left:6px solid #7C3AED;
    padding:18px 20px;
    border-radius:12px;
    margin-top:15px;
    font-family:Segoe UI;
">

<h3 style="
    margin-top:0;
    color:#0F172A;
">
Interprétation métier
</h3>

<p style="color:#334155; line-height:1.7;">

Le traitement des valeurs manquantes améliore la qualité des données utilisées pour la segmentation client.

Une mauvaise gestion des données manquantes peut perturber :
</p>

<ul style="color:#334155; line-height:1.7;">
<li>les calculs de distance ;</li>
<li>les regroupements de clients ;</li>
<li>la qualité des clusters.</li>
</ul>

</div>

<div style="
    display:inline-block;
    border-left:5px solid #06B6D4;
    background:#ECFEFF;
    padding:10px 14px;
    border-radius:10px;
    font-family:Segoe UI;
    margin-top:15px;
    margin-bottom:10px;
    box-shadow:0 2px 8px rgba(15,23,42,0.06);
">

<h3 style="
    margin:0;
    color:#0F172A;
    font-size:18px;
    font-weight:600;
">
 •	Encodage
</h3>

</div>

In [6]:
# ============================================
# ENCODAGE DES VARIABLES
# ============================================

categorical_columns = [
    "Education",
    "Marital_Status"
]

encoder = LabelEncoder()

for col in categorical_columns:

    df[col] = encoder.fit_transform(
        df[col]
    )

print("Encodage terminé")

df.head()

Encodage terminé

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,2,4,58138.0,0,0,04/09/2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,2,4,46344.0,1,1,08/03/2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,2,5,71613.0,0,0,21/08/2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,2,5,26646.0,1,0,10/02/2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,4,3,58293.0,1,0,19/01/2014,94,173,...,5,0,0,0,0,0,0,3,11,0

<div style="
    background:#F8FAFC;
    border-left:6px solid #7C3AED;
    padding:18px 20px;
    border-radius:12px;
    margin-top:15px;
    font-family:Segoe UI;
">

<h3 style="
    margin-top:0;
    color:#0F172A;
">
Interprétation métier
</h3>

<p style="color:#334155; line-height:1.7;">

Les algorithmes de clustering nécessitent des données numériques pour calculer les similarités entre clients.

L’encodage transforme les variables textuelles en valeurs exploitables par les modèles.
</p>

</div>

<div style="
    display:inline-block;
    border-left:5px solid #06B6D4;
    background:#ECFEFF;
    padding:10px 14px;
    border-radius:10px;
    font-family:Segoe UI;
    margin-top:15px;
    margin-bottom:10px;
    box-shadow:0 2px 8px rgba(15,23,42,0.06);
">

<h3 style="
    margin:0;
    color:#0F172A;
    font-size:18px;
    font-weight:600;
">
 •	Normalisation
</h3>

</div>

In [8]:
# ============================================
# TRAITEMENT DES DATES AVANT NORMALISATION
# ============================================

# Conversion de la date client
df["Dt_Customer"] = pd.to_datetime(
    df["Dt_Customer"],
    dayfirst=True,
    errors="coerce"
)

# Création d'une variable numérique : ancienneté client
CURRENT_DATE = pd.to_datetime("2026-05-12")

df["Customer_Tenure_Days"] = (
    CURRENT_DATE - df["Dt_Customer"]
).dt.days

# Suppression de la colonne date originale
df = df.drop("Dt_Customer", axis=1)

print("Date transformée en ancienneté client")

Date transformée en ancienneté client

In [9]:
# ============================================
# NORMALISATION
# ============================================

scaler = StandardScaler()

scaled_data = scaler.fit_transform(df)

scaled_df = pd.DataFrame(
    scaled_data,
    columns=df.columns
)

print("Normalisation terminée")

scaled_df.head()

Normalisation terminée

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,...,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Customer_Tenure_Days
0,-0.020999,-0.985345,-0.350141,0.251004,0.235696,-0.825218,-0.929894,0.307039,0.983781,1.551577,...,-0.28014,-0.28383,-0.28014,-0.262111,-0.11651,-0.097282,0.0,0.0,2.388846,1.531185
1,-1.053058,-1.235733,-0.350141,0.251004,-0.235454,1.032559,0.906934,-0.383664,-0.870479,-0.636301,...,-0.28014,-0.28383,-0.28014,-0.262111,-0.11651,-0.097282,0.0,0.0,-0.418612,-1.190545
2,-0.447070,-0.317643,-0.350141,1.180340,0.773999,-0.825218,-0.929894,-0.798086,0.362723,0.570804,...,-0.28014,-0.28383,-0.28014,-0.262111,-0.11651,-0.097282,0.0,0.0,-0.418612,-0.205773
3,0.181716,1.268149,-0.350141,1.180340,-1.022355,1.032559,-0.929894,-0.798086,-0.870479,-0.560857,...,-0.28014,-0.28383,-0.28014,-0.262111,-0.11651,-0.097282,0.0,0.0,-0.418612,-1.061881
4,-0.082614,1.017761,1.428354,-0.678332,0.241888,1.032559,-0.929894,1.550305,-0.389085,0.419916,...,-0.28014,-0.28383,-0.28014,-0.262111,-0.11651,-0.097282,0.0,0.0,-0.418612,-0.953012

<div style="
    background:#F8FAFC;
    border-left:6px solid #7C3AED;
    padding:18px 20px;
    border-radius:12px;
    margin-top:15px;
    font-family:Segoe UI;
">

<h3 style="
    margin-top:0;
    color:#0F172A;
">
Interprétation métier
</h3>

<p style="color:#334155; line-height:1.7;">

La normalisation permet d’éviter qu’une variable domine artificiellement les calculs de distance utilisés par les algorithmes de clustering.

Toutes les variables sont ainsi placées sur une échelle comparable.
</p>

</div>

<div style="
    display:inline-block;
    border-left:5px solid #06B6D4;
    background:#ECFEFF;
    padding:10px 14px;
    border-radius:10px;
    font-family:Segoe UI;
    margin-top:15px;
    margin-bottom:10px;
    box-shadow:0 2px 8px rgba(15,23,42,0.06);
">

<h3 style="
    margin:0;
    color:#0F172A;
    font-size:18px;
    font-weight:600;
">
 •	PCA-REDUCTION DE DIMENSION
</h3>

</div>

In [10]:
# ============================================
# PCA
# ============================================

pca = PCA(n_components=2)

pca_components = pca.fit_transform(
    scaled_df
)

pca_df = pd.DataFrame(
    pca_components,
    columns=["PCA1", "PCA2"]
)

print("PCA appliqué avec succès")

pca_df.head()

PCA appliqué avec succès

       PCA1      PCA2
0  3.828824  0.351067
1 -2.417705 -0.221427
2  1.615270 -0.297472
3 -2.549660 -1.577777
4 -0.471320 -0.159206

In [12]:
# ============================================
# VISUALISATION PCA
# ============================================

fig = px.scatter(
    pca_df,

    x="PCA1",
    y="PCA2",

    color="PCA1",

    color_continuous_scale=[
        "#06B6D4",
        "#7C3AED",
        "#0F172A"
    ],

    title="Projection PCA des clients"
)

fig.update_layout(
    template="plotly_white",

    height=700,

    title_x=0.5,

    coloraxis_showscale=False
)

fig.show()

<div style="
    background:#F8FAFC;
    border-left:6px solid #7C3AED;
    padding:18px 20px;
    border-radius:12px;
    margin-top:15px;
    font-family:Segoe UI;
">

<h3 style="
    margin-top:0;
    color:#0F172A;
">
Interprétation métier
</h3>

<p style="color:#334155; line-height:1.7;">

La PCA permet de réduire la complexité des données tout en conservant l’essentiel de l’information.

Cette projection facilite :
</p>

<ul style="color:#334155; line-height:1.7;">
<li>la visualisation des groupes de clients ;</li>
<li>la réduction du bruit dans les données ;</li>
<li>l’amélioration des performances du clustering.</li>
</ul>

</div>

In [13]:
# ============================================
# SAUVEGARDE
# ============================================

scaled_df.to_csv(
    "../data/processed/cluster_scaled.csv",
    index=False
)

pca_df.to_csv(
    "../data/processed/cluster_pca.csv",
    index=False
)

print("Données sauvegardées avec succès")

Données sauvegardées avec succès